# Generated by Django 4.0 on 2021-12-09 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('job', 'job'), ('story', 'story'), ('comment', 'comment'), ('poll', 'poll'), ('pollopt', 'pollopt')], max_length=200, null=True)),
                ('author', models.CharField(max_length=200, null=True)),
                ('created', models.DateField(null=True)),
                ('comment_count', models.IntegerField(null=True)),
                ('url', models.URLField(null=True)),
                ('content', models.TextField(null=True)),
                ('title', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('job', 'job'), ('story', 'story'), ('comment', 'comment'), ('poll', 'poll'), ('pollopt', 'pollopt')], max_length=200, null=True)),
                ('author', models.CharField(max_length=200, null=True)),
                ('created', models.DateField(null=True)),
                ('comment_count', models.IntegerField(null=True)),
                ('url', models.URLField(null=True)),
                ('content', models.TextField(null=True)),
                ('title', models.CharField(max_length=500)),
                ('score', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('job', 'job'), ('story', 'story'), ('comment', 'comment'), ('poll', 'poll'), ('pollopt', 'pollopt')], max_length=200, null=True)),
                ('author', models.CharField(max_length=200, null=True)),
                ('created', models.DateField(null=True)),
                ('title', models.CharField(max_length=500)),
                ('comment_count', models.IntegerField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('url', models.URLField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('job', 'job'), ('story', 'story'), ('comment', 'comment'), ('poll', 'poll'), ('pollopt', 'pollopt')], max_length=200, null=True)),
                ('author', models.CharField(max_length=200, null=True)),
                ('created', models.DateField(null=True)),
                ('comment_count', models.IntegerField(null=True)),
                ('url', models.URLField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('poll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll_options', to='news.poll')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('job', 'job'), ('story', 'story'), ('comment', 'comment'), ('poll', 'poll'), ('pollopt', 'pollopt')], max_length=200, null=True)),
                ('author', models.CharField(max_length=200, null=True)),
                ('created', models.DateField(null=True)),
                ('comment_count', models.IntegerField(null=True)),
                ('parent_comment_id', models.IntegerField(null=True)),
                ('content', models.TextField(null=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='news.job')),
                ('poll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='news.poll')),
                ('poll_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll_options', to='news.polloption')),
                ('story', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.story')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
