# Generated by Django 4.0 on 2021-12-09 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackerNewsItem',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('job', 'job'), ('story', 'story'), ('comment', 'comment'), ('poll', 'poll'), ('pollopt', 'pollopt')], max_length=200, null=True)),
                ('author', models.CharField(max_length=200, null=True)),
                ('created', models.DateField(null=True)),
                ('title', models.CharField(max_length=500, null=True)),
                ('comment_count', models.IntegerField(null=True)),
                ('content', models.TextField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('url', models.URLField(null=True)),
                ('parent_comment_id', models.IntegerField(null=True)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_comments', to='news.comment')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_jobs', to='news.job')),
                ('poll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_polls', to='news.poll')),
                ('poll_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_poll_options', to='news.polloption')),
                ('story', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_story', to='news.story')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
