# Generated by Django 4.0 on 2021-12-09 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_hackernewsitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackernewsitem',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hackernewsitem',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_comments', to='news.comment'),
        ),
        migrations.AlterField(
            model_name='hackernewsitem',
            name='comment_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hackernewsitem',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hackernewsitem',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hackernewsitem',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_jobs', to='news.job'),
        ),
        migrations.AlterField(
            model_name='hackernewsitem',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_polls', to='news.poll'),
        ),
        migrations.AlterField(
            model_name='hackernewsitem',
            name='poll_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_poll_options', to='news.polloption'),
        ),
        migrations.AlterField(
            model_name='hackernewsitem',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hackernewsitem',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_story', to='news.story'),
        ),
        migrations.AlterField(
            model_name='hackernewsitem',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hackernewsitem',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
