# Generated by Django 4.0 on 2021-12-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_hackernewsitem_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackernewsitem',
            name='parent_comment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
