# Generated by Django 4.0 on 2021-12-09 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_hackernewsitem_parent_comment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent_comment_id',
            new_name='parent_comment',
        ),
        migrations.AlterField(
            model_name='comment',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.job'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.poll'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='poll_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.polloption'),
        ),
    ]
