# Generated by Django 4.0 on 2021-12-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_parent_comment_id_comment_parent_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
